"""
Django settings for HealthBridge project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (must be loaded BEFORE using os.getenv)
env_path = BASE_DIR / '.env'
load_dotenv(env_path)
print(f"Loading .env from: {env_path}")  # Debug line


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-e3h6v-cied4y2vt^icj+c_d!v1jsx^o=fza_4$gb_2t4-jy4+j')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Allow any Render.com subdomain + localhost for development
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*.onrender.com,localhost,127.0.0.1').split(',')
# Clean whitespace from hosts
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS]

# If running on Render, also allow the specific render URL
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',  # django-storages for custom storage backends
    
    # Core app (will keep CustomUser model here)
    'healthbridge_app',
    
    # Modular apps
    'landing',
    'login',
    'registration',
    'dashboard',
    'profile',
    'donations',
    'requests',
    'notifications',
    'administrator',
]

AUTH_USER_MODEL = 'healthbridge_app.CustomUser'

AUTHENTICATION_BACKENDS = [
    'healthbridge_app.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',  # keep default for admin
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
]

ROOT_URLCONF = 'HealthBridge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Look for templates in project root
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': True,  # Force template reload in development
        },
    },
]

WSGI_APPLICATION = 'HealthBridge.wsgi.application'


# Database - Supabase PostgreSQL (Required)
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Get DATABASE_URL from environment (must be set in .env file)
database_url = os.getenv('DATABASE_URL')

if not database_url:
    raise ValueError(
        "DATABASE_URL not found in environment variables. "
        "Please set it in your .env file with your Supabase connection string."
    )

DATABASES = {
    "default": dj_database_url.config(
        default=database_url,
        conn_max_age=600,  # Keep connections alive for 10 minutes
        conn_health_checks=True,  # Verify connection health
        ssl_require=True,  # Require SSL for Supabase
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # Look for static files in project root
STATIC_ROOT = BASE_DIR / "staticfiles"
# Cache configuration for faster autocomplete
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'healthbridge-cache',
        'TIMEOUT': 300,  # 5 minutes default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 🆕 Media files configuration - Supabase Storage
MEDIA_URL = '/media/'  # Keep for backward compatibility

# Supabase Storage settings
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_KEY')
SUPABASE_BUCKET_NAME = os.getenv('SUPABASE_BUCKET_NAME', 'medicine-images')

# Use Supabase Storage as default file storage (Django 5.x uses STORAGES)
STORAGES = {
    "default": {
        "BACKEND": "HealthBridge.supabase_storage.SupabaseStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Auth redirects
LOGIN_URL = '/login/'             # where @login_required sends unauthenticated users
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Email configuration
# Try Mailgun first (Render's recommended free option)
if os.getenv('MAILGUN_SMTP_LOGIN'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.mailgun.org'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.getenv('MAILGUN_SMTP_LOGIN')
    EMAIL_HOST_PASSWORD = os.getenv('MAILGUN_SMTP_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('MAILGUN_SMTP_LOGIN', 'noreply@healthbridge.app')
# Try SendGrid (alternative free option - 100 emails/day)
elif os.getenv('SENDGRID_API_KEY'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.sendgrid.net'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'apikey'
    EMAIL_HOST_PASSWORD = os.getenv('SENDGRID_API_KEY')
    DEFAULT_FROM_EMAIL = os.getenv('SENDGRID_FROM_EMAIL', 'noreply@healthbridge.app')
# Gmail configuration (works locally and on Render with proper setup)
elif os.getenv('EMAIL_HOST_USER') and os.getenv('EMAIL_HOST_PASSWORD'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False  # Use TLS on port 587, not SSL
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')
else:
    # Fallback - use console backend if no credentials configured
    # This prevents crashes but emails won't actually send
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 25
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    DEFAULT_FROM_EMAIL = 'noreply@healthbridge.app'
    print("WARNING: No email credentials configured. Using console backend.")

SERVER_EMAIL = DEFAULT_FROM_EMAIL
    
# Email timeout to prevent worker timeouts on Render
EMAIL_TIMEOUT = 10  # Reduced from 30 to prevent worker timeout
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'healthbridge_app': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'login': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'dashboard': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}